/*
 
    Error Types and Handling

*/

try{
    a + b
}
catch(error){
    console.log("Error has been saved to the error log")
}